/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as PostsIdCommentsRouteImport } from './routes/posts.$id.comments'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostsRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const PostsIdCommentsRoute = PostsIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => PostsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/admin/posts': typeof AdminPostsRoute
  '/posts/$id': typeof PostsIdRouteWithChildren
  '/posts/$id/comments': typeof PostsIdCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/admin/posts': typeof AdminPostsRoute
  '/posts/$id': typeof PostsIdRouteWithChildren
  '/posts/$id/comments': typeof PostsIdCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/admin/posts': typeof AdminPostsRoute
  '/posts/$id': typeof PostsIdRouteWithChildren
  '/posts/$id/comments': typeof PostsIdCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/posts'
    | '/admin/posts'
    | '/posts/$id'
    | '/posts/$id/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/posts'
    | '/admin/posts'
    | '/posts/$id'
    | '/posts/$id/comments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/posts'
    | '/admin/posts'
    | '/posts/$id'
    | '/posts/$id/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/posts/$id/comments': {
      id: '/posts/$id/comments'
      path: '/comments'
      fullPath: '/posts/$id/comments'
      preLoaderRoute: typeof PostsIdCommentsRouteImport
      parentRoute: typeof PostsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PostsIdRouteChildren {
  PostsIdCommentsRoute: typeof PostsIdCommentsRoute
}

const PostsIdRouteChildren: PostsIdRouteChildren = {
  PostsIdCommentsRoute: PostsIdCommentsRoute,
}

const PostsIdRouteWithChildren =
  PostsIdRoute._addFileChildren(PostsIdRouteChildren)

interface PostsRouteChildren {
  PostsIdRoute: typeof PostsIdRouteWithChildren
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsIdRoute: PostsIdRouteWithChildren,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
